global:
  resolve_timeout: 5m

route:
  receiver: telegram
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 2m
  repeat_interval: 2h

receivers:
  - name: telegram
    telegram_configs:
      - bot_token: ${ALERTMANAGER_TELEGRAM_BOT_TOKEN}
        chat_id: ${ALERTMANAGER_TELEGRAM_CHAT_ID}
        parse_mode: Markdown
        message: |
          *{{ .Status | toUpper }}* {{ .CommonLabels.alertname }}\n
          {{ range .Alerts }}â€¢ {{ .Annotations.summary }}\n{{ if .Annotations.description }}  _{{ .Annotations.description }}_\n{{ end }}{{ end }}
        disable_notifications: false
