services:
  hmm_deck:
    depends_on:
      REPLACE_ME_OPS_SERVICE:
        condition: service_started

  hmm_allocator:
    depends_on:
      REPLACE_ME_OPS_SERVICE:
        condition: service_started
